package update, regex update and using in devcontainer
quicky84/commentimg pull request #1
Opened 2020-12-03 23:43 UTC by dbrandes-welfenlab

Hi,

thanks for this great extension for code. It makes documentation of code much better. I need it in devcontainers and want to use it together with the drawio-extension (use .drawio.svg and .drawio.png as extensions), so I need the fixes from this request. It would be cool if you would integrate this into your code and push a new release to the vscode extension repo.

best regards,

Daniel

2020-12-04 12:43 UTC, vnermolaev requested changes
Thanks for your effort! I have requested only a few small changes.

2020-12-04 12:43 UTC, vnermolaev commented on README.md
> +to use in devcontainer, two options are there:
Would you start sentences with a capital letter?

2020-12-04 12:43 UTC, vnermolaev commented on package.json
> +    "publisher": "quicky84",
Please keep the original name

2020-12-04 12:43 UTC, vnermolaev commented on package.json
> +					"description": "Override path to workspace to display images from. Leave Empty to use default one. Useful for devcontainers. this is relative to homedir if commentimg.home_dir_override is set.",
Would you align these descriptions with those in README?

2020-12-04 17:40 UTC, dbrandes-welfenlab commented on README.md
> +to use in devcontainer, two options are there:
Hi,

thanks for the fast reply and the comments. I tried to fix them.

I fixed this, sorry for the spelling issues. If you find more, please write again or fix it by yourself if you like.

2020-12-04 17:40 UTC, dbrandes-welfenlab commented on package.json
> +    "publisher": "quicky84",
I have changed it back, sorry for this. I locally set it to your vscode name (hope this was you), because I could not package it with the vs code tools to test it in devcontainer.

2020-12-04 17:40 UTC, dbrandes-welfenlab commented on package.json
> +					"description": "Override path to workspace to display images from. Leave Empty to use default one. Useful for devcontainers. this is relative to homedir if commentimg.home_dir_override is set.",
I have joined these and now these are the same (hope you mean this.).

Additionally I have another small request to you:

Can you add a licence file to your extension?

best regards,

Daniel

2020-12-14 10:20 UTC, vnermolaev approved these changes

2020-12-14 10:20 UTC, merged